namespace Xchain.Tests.Templates.FlowA;

// [Collection] and [CollectionDefinition] are generated by FlowAChain via CollectionChainGenerator.
// Signals itself so VerifyIsolation can await the completion of the full FlowA chain.
public partial class Step_03_Import(CollectionChainContextFixture chain)
    : ImportDataChain<Step_03_Import, Step_02_Project>(chain, "Small payload");
