namespace Xchain.Tests.Templates.FlowA;

// CRTP: passing itself as TSelf means output keys are automatically namespaced to this type.
//   output.ClientId<Step_01_Client>() → key "Xchain.Tests.Templates.FlowA.Step_01_Client_ClientId"
// The equivalent in FlowB produces a different key, so the two flows never collide.
//
// [TestCaseOrderer] is NOT declared here — it is inherited from CreateClientChain<T>.
// [Collection] and [CollectionDefinition] are generated by FlowAChain via CollectionChainGenerator.
public partial class Step_01_Client(CollectionChainContextFixture chain)
    : CreateClientChain<Step_01_Client>(chain);
