namespace Xchain.Tests.Templates.FlowD;

// Middle/end step with a generated timeout fixture (WorkflowD uses Then<Step_02>(TimeSpan.FromMinutes(30))).
// [Collection] and [CollectionDefinition] are generated by WorkflowD via CollectionChainGenerator,
// and the definition uses __XchainTimeout_Step_02NextFixture : CollectionChainNextFixture<Step_01, Step_02>.
public partial class Step_02(CollectionChainContextFixture chain)
    : CreateProjectChain<Step_02, Step_01>(chain);
