namespace Xchain.Tests.Templates.FlowD;

// Start of the timeout-fixture chain (WorkflowD).
// [Collection] and [CollectionDefinition] are generated by WorkflowD via CollectionChainGenerator.
public partial class Step_01(CollectionChainContextFixture chain)
    : CreateClientChain<Step_01>(chain);
