using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Xchain.Generators;

[Generator]
public sealed class ChainOutputSchemaGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var schemaTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is TypeDeclarationSyntax { AttributeLists.Count: > 0 } and (ClassDeclarationSyntax or InterfaceDeclarationSyntax),
                transform: static (ctx, ct) => GetSchemaInfo(ctx, ct))
            .Where(static x => x is not null);

        context.RegisterSourceOutput(schemaTypes, static (ctx, info) =>
        {
            var (hintName, source) = Generate(info!);
            ctx.AddSource(hintName, source);
        });
    }

    private static SchemaInfo? GetSchemaInfo(GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        var cls = (TypeDeclarationSyntax)ctx.Node;
        if (ctx.SemanticModel.GetDeclaredSymbol(cls, ct) is not INamedTypeSymbol symbol)
            return null;

        bool hasAttr = symbol.GetAttributes().Any(static a =>
            a.AttributeClass?.Name is "ChainOutputSchemaAttribute" or "ChainOutputSchema");
        if (!hasAttr) return null;

        var ns = symbol.ContainingNamespace?.IsGlobalNamespace == true
            ? string.Empty
            : (symbol.ContainingNamespace?.ToDisplayString() ?? string.Empty);

        var properties = symbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
            .Select(p => new PropertyInfo(p.Name, p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)))
            .ToList();

        if (properties.Count == 0) return null;

        return new SchemaInfo(symbol.Name, ns, properties);
    }

    private static (string HintName, string Source) Generate(SchemaInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();

        bool hasNs = !string.IsNullOrEmpty(info.Namespace);
        if (hasNs)
        {
            sb.AppendLine($"namespace {info.Namespace}");
            sb.AppendLine("{");
        }

        var indent = hasNs ? "    " : "";
        sb.AppendLine($"{indent}public static class {info.ClassName}Extensions");
        sb.AppendLine($"{indent}{{");

        foreach (var prop in info.Properties)
        {
            sb.AppendLine($"{indent}    public static global::Xchain.TestOutput<T, {prop.TypeFqn}> {prop.Name}<T>(");
            sb.AppendLine($"{indent}        this global::Xchain.TestChainOutput output)");
            sb.AppendLine($"{indent}        => new(output, nameof({info.ClassName}.{prop.Name}));");
            sb.AppendLine();
        }

        sb.AppendLine($"{indent}}}");

        if (hasNs)
            sb.AppendLine("}");

        return ($"ChainOutputSchema_{info.ClassName}.g.cs", sb.ToString());
    }

    private sealed record SchemaInfo(string ClassName, string Namespace, List<PropertyInfo> Properties);
    private sealed record PropertyInfo(string Name, string TypeFqn);
}
