namespace Xchain.Tests.Templates.FlowB;

// [Collection] and [CollectionDefinition] are generated by FlowBChain via CollectionChainGenerator.
// Signals itself so both VerifyIsolation and FlowC can await its completion.
public partial class Step_03_Import(CollectionChainContextFixture chain)
    : ImportDataChain<Step_03_Import, Step_02_Project>(chain, "Large payload");
