namespace Xchain.Tests.Templates.FlowB;

// [Collection] and [CollectionDefinition] are generated by FlowBChain via CollectionChainGenerator.
public partial class Step_02_Project(CollectionChainContextFixture chain)
    : CreateProjectChain<Step_02_Project, Step_01_Client>(chain);
