namespace Xchain.Tests.Templates.FlowB;

// Identical structure to FlowA.Step_01_Client — same template, different namespace.
// The namespace makes the types distinct: FullName resolves to
//   "Xchain.Tests.Templates.FlowB.Step_01_Client"
// so output keys and awaiter keys are completely isolated from FlowA's Step_01_Client.
// Both flows start in parallel — neither waits for the other.
//
// [Collection] and [CollectionDefinition] are generated by FlowBChain via CollectionChainGenerator.
public partial class Step_01_Client(CollectionChainContextFixture chain)
    : CreateClientChain<Step_01_Client>(chain);
