using FlowA = Xchain.Tests.Templates.FlowA;
using FlowB = Xchain.Tests.Templates.FlowB;

namespace Xchain.Tests.Templates.FlowC;

// Cross-flow collection that fans in from two independent chains.
// [Collection] and [CollectionDefinition] are generated by FlowCChain via CollectionChainGenerator.
// The definition awaits FlowA.Step_01_Client AND FlowB.Step_03_Import before starting.
[TestCaseOrderer("Xchain.TestChainOrderer", "Xchain")]
public partial class Step_01_Project(CollectionChainContextFixture chain)
{
    [ChainFact(Link = 1, Name = "Create cross-flow project from FlowA client and FlowB import")]
    public void CreateProject() =>
        chain.LinkWithCollectionUnless<Exception, FlowA.Step_01_Client>(chain.Output.ClientId<FlowA.Step_01_Client>().Key, output =>
        {
            var clientId = output.ClientId<FlowA.Step_01_Client>().Get();
            var importId = output.ImportId<FlowB.Step_03_Import>().Get();
            output.ProjectId<Step_01_Project>().Put($"cross-flow-project|client={clientId}|import={importId}");
        });

    [ChainFact(Link = 2, Name = "Verify cross-flow project was created")]
    public void VerifyProject() =>
        chain.LinkUnless<Exception>(output =>
        {
            var projectId = output.ProjectId<Step_01_Project>().Get();
            Assert.Contains("cross-flow-project", projectId);
        });
}
